spring:
  application:
    name: pay-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://192.168.56.22:3306/pay-service?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: mysql

mybatis-plus:
  #  global-config:
  #    db-config:
  #      table-prefix: T_A1_
  #      id-type: uuid
  mapper-locations: classpath*:DB/mapper/*.xml
  type-aliases-package: com.cesgroup.springcloud.entity
  configuration:
    cache-enabled: false
logging:
  level:
    com.cesgroup.springcloud.mapper: debug